export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";
export const ADD_REVIEW_RESET = "ADD_REVIEW_RESET";

export const ADMIN_PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const ADMIN_PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const ADMIN_PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST"
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS"
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL"
export const ADMIN_PRODUCT_DELETE_RESET = "ADMIN_PRODUCT_DELETE_RESET"

export const ADMIN_PRODUCT_UPDATE_REQUEST = "ADMIN_PRODUCT_UPDATE_REQUEST";
export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAIL = "ADMIN_PRODUCT_UPDATE_FAIL";
export const ADMIN_PRODUCT_UPDATE_RESET = "ADMIN_PRODUCT_UPDATE_RESET";



export const ADMIN_PRODUCT_REVIEWS_REQUEST = "ADMIN_PRODUCT_REVIEWS_REQUEST"
export const ADMIN_PRODUCT_REVIEWS_SUCCESS = "ADMIN_PRODUCT_REVIEWS_SUCCESS"
export const ADMIN_PRODUCT_REVIEWS_FAIL = "ADMIN_PRODUCT_REVIEWSFAILT"

export const ADMIN_REVIEW_DELETE_REQUEST = "ADMIN_REVIEW_DELETE_REQUEST";
export const ADMIN_REVIEW_DELETE_SUCCESS = "ADMIN_REVIEW_DELETE_SUCCESS";
export const ADMIN_REVIEW_DELETE_FAIL = "ADMIN_REVIEW_DELETE_FAIL";
export const ADMIN_REVIEW_DELETE_RESET = "ADMIN_REVIEW_DELETE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";